ceph/pulpito-ng

src/lib/utils.js

This PR is a fix for issue #9 where the date was initially in the format `yy-mm-dd hh:mm:ss` and the year was changed to `yyyy` format.

lib/utils.js: changed year format from yy to yyyy

---

src/App.tsx

The original pulpito used routes like /:run/:job_id. While we prefer the more explicit routes, it'll be helpful if URLs are mostly backwards compatible.

Add routes for backwards compatibility

---

src/pages/Job/index.js

Fixed issue #7
For e.g. -
trociny has schedulded the job on 24 June as shown in ss-
and we can see the following ss that it's showing correct started time i.e. 2 days ago as its 26 June today

pages/Job/index.js: fix job started time

---

src/pages/Run/index.tsx

This PR solves issue #2 which adds a kill run button that will kill all jobs in the current run. It currently uses a mock API endpoint for success alert, needs to be connected to the `teuthology-api`

Implement kill-run button

---

src/pages/Run/index.tsx

Reverts ceph/pulpito-ng#25
At first I thought it would be nicer to avoid reverting, but #28 would need more work first, and then #27 would need to resolve merge conflicts through a large number of commits. If we revert and re-file the original PR, we don't have to wait on those other two things to move forward.
There will be a merge conflict with #25s commit, but it will be far more simple being just the one commit.

Revert "Implement kill-run button"

---

src/pages/Runs/index.tsx

Fixed Issue #10 
The date filter box is now aligned to other widgets.

pages/Runs/index.tsx: fixed date filter box alignment 

---

src/lib/paddles.ts

This PR fixes issue #34 by adding the `VITE_` prefix to `PADDLES_SERVER` variable.

src/lib/paddles.ts: Add VITE_ prefix to env variables

---

src/components/Link/index.jsx
src/pages/Run/index.tsx

The "see similar runs" links we provide were worded poorly and spaced weirdly.

Run: Adjust filter links

---

src/components/JobList/index.tsx

This truncates the longer strings to 200 chars.

JobList: Hover on status col shows failure reason

---

src/components/JobList/index.tsx
src/lib/utils.js
src/pages/Job/index.jsx

This is more helpful than linking directly to teuthology.log, which may not even exist yet.

Job{,List}: Link to job archive directories

---

package-lock.json
package.json
src/components/AppBar/index.jsx
src/components/Login/index.jsx
src/index.tsx
src/lib/teuthologyAPI.ts

1. Login button redirects to teuthology API's login
2. User data is saved in cookies by the callback by this PR: https://github.com/ceph/teuthology-api/pull/12
3. Parse cookie data
For local setup, `.env` file:
```
VITE_PADDLES_SERVER=http://localhost:8080/
VITE_TEUTHOLOGY_API=http://localhost:8082/
```
TODO (refactoring):

Github Authentication

---

src/components/Login/index.jsx
src/lib/teuthologyAPI.ts

#52 was merged in a state where a missing `VITE_TEUTHOLOGY_API` env var would cause all routes to render as a blank white page. If the setting was present but incorrect, a broken Login button would be rendered.

Fix breakage if teuthology-api endpoint is unconfigured

---

src/lib/paddles.d.ts
src/pages/Run/index.tsx

Additionally, hide buttons when there are no jobs with their corresponding status.

Run: Label filter buttons with job counts

---

tsconfig.json

This fixes "Property 'env' does not exist on type 'ImportMeta'".

tsconfig.json: Move types into compilerOptions

---

Dockerfile
README.md
start_container.sh
vite.config.js

Allow hot reload in Development mode for
pulpito-ng. This saves a lot more time
when developing with other tech stacks.

src: Add hot reload option for development

---

package.json
src/App.tsx
src/components/CodeBlock/index.jsx
src/components/ErrorFallback/index.tsx
src/components/JobList/index.tsx
src/pages/Job/index.jsx

This is the page where I first noticed this crash: https://pulpito-ng.ceph.com/runs/mchangir-2023-10-14_16:12:46-fs-wip-mchangir-mgr-snap_schedule-support-subvol-and-group-arguments-distro-default-smithi

Improve error handling and fix a crash

---

src/components/JobList/index.tsx

Somehow, the filter call was causing a render loop. Memoizing fixes that.

JobList: Fix a hang when sorting

---

src/components/JobList/index.tsx
src/components/RunList/index.tsx
src/lib/table.ts

This PR:
1. Adds border to table cells
2. disable column action buttons (three vertical dots) from columns "link", "status", and "user". This makes some space in header column of the table for displaying text. Its only disabled for these fields because column actions can be useful to hide a column from the table and these are essential columns which probably don't need to be removed from view. 
3. Link column is moved to left most to give better collected view of information.
4. "scheduled" column is edited so date and time show up in different lines (like in pulpito). Helps to reduce column width. 
5. Only show 8 letters of "hash" column. Original pulpito has a similar view. Helps to reduce column width. 
6. Make all status columns at the end ("fail", "pass", etc) of same width to bring …

Add table cell border (and other table UI improvements)

---

src/components/RunList/index.tsx
src/lib/paddles.d.ts

Also adds the hidden-by-default 'total' column.

RunList: Show job totals in footer

---

src/components/JobList/index.tsx
src/lib/paddles.d.ts

This will allow to search across all fields of all rows, in job list.
On a run pgae, click on the search icon at top right. There you can search for any data in the table (os type, job id, job description, task name, etc). 
Here I searched for "post_upgrade_checks" and it filtered by task `fs.post_upgrade_checks`. Run: https://deploy-preview-86--pulpito.netlify.app/runs/teuthology-2024-09-13_21:08:03-orch-squid-distro-default-smithi

JobList: add Global Filter

---

src/components/Alert/index.tsx
src/components/KillButton/index.tsx
src/components/Login/index.jsx
src/lib/paddles.d.ts
src/lib/teuthologyAPI.d.ts
src/lib/teuthologyAPI.ts
src/pages/Run/index.tsx

This PR solves issue #2 which adds a kill run button that will kill all jobs in the current run. It currently uses a mock API endpoint for success alert, needs to be connected to the teuthology-api
https://github.com/ceph/pulpito-ng/assets/50358181/3e51bc1f-dfd3-40be-9bc7-d6bb38406cfe

pages/Run/index.tsx: Add kill run button

---

src/components/RunList/index.tsx

Related: https://github.com/ceph/paddles/pull/129

RunList: Filter by username

---

src/components/JobHistory/index.jsx
src/components/JobList/index.tsx
src/lib/paddles.d.ts
src/lib/paddles.ts
src/pages/Job/index.jsx

Display last 25 job runs of that description.
The reason why the history is shown after a button click (and hidden by default) is to avoid an extra call to paddles if user is not looking for job-history information and also to avoid information overload for users. 
Output example:

Show JobHistory on Job Page

---

src/components/RunList/index.tsx
src/lib/paddles.ts
src/lib/table.ts

- Use custom filter to show filter inputs outside the table
- Add a button to expand/hide filter options
- Display sort button only on hover over the column title
- Disable column action buttons (all of it's functions can be performed with sort, filter, and show/hide column buttons on corner-right)
Column Action button options:
Output:

RunList: use Custom filter

---

src/components/RunList/index.tsx

Replaced xs with sx in <Grid item> and applied consistent maxWidth to inputs.
Fixed overlap caused by scheduled date picker.
Inputs now align cleanly, even with dynamic column visibility.

Bug filter menu in RunList overlap #99
